Часть 6: Интеграционное (acceptance) тестирование
kshnyakin/think-over-flow pull request #3
Opened 2024-01-31 11:53 UTC by kshnyakin

1. Реализовать следующие истории, начиная с acceptance-тестов (если они уже реализованы, покрыть acceptance-тестами):
  - Пользователь может создавать вопрос
  - Пользователь может просматривать список вопросов
  - Пользователь, находясь на странице вопроса, может написать ответ на вопрос (т.е. форма нового ответа должна быть прямо на странице вопроса, без перехода на другую страницу)
  - Пользователь может просматривать вопрос и ответы к нему.

 2. Добавить аутентификацию к проекту, покрыть acceptance-тестами следующие сценарии:
  - Пользователь может войти в систему
  - Пользователь может выйти из системы
  - Пользователь может зарегистрироваться в системе

 3. Реализовать следующие истоиии:
  - Только аутентифицированный пользователь может создавать вопросы и ответы
  - Автор может удалить свой вопрос или ответ, но не может удалить чужой вопрос/ответ

2024-02-16 09:42 UTC, vkurennov requested changes

2024-02-16 09:42 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if answer.author_id == current_user.id
такая проверка нужна будет во многих местах, хорошо бы ее вынести в метод модели User, например, `User#author_of?` (и не забудь тестами покрыть этот метод в тестах модели)

2024-02-16 09:42 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if question.author_id == current_user.id
Замени на вызов `User#author_of?`

2024-02-16 09:42 UTC, vkurennov commented on app/views/answers/_answer.html.erb
> +    <% if current_user&.id == question.author_id %>
Замени на вызов `User#author_of?`

2024-02-16 09:42 UTC, vkurennov commented on app/views/answers/_answer.html.erb
> +<tr>
используй slim, erb  довольно громоздкий, в большинстве проектов используется slim/haml
 чтобы руками не переписывать все виды, там есть конвертер: https://github.com/slim-template/html2slim (виды devise можешь не переводить, только свои)

2024-02-16 09:42 UTC, vkurennov commented on app/views/questions/_question.html.erb
> +    <% if current_user&.id == question.author_id %>
Замени на вызов `User#author_of?`

2024-02-16 09:42 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    = f.hidden_field :author_id, value: current_user.id, name: "answer[author_id]"
не нужно передвать скрытые поля, это не безопасно, т.к. можно подменить значения. автора ты можешь взять в контроллере через current_user. А для question нужно использовать вложенные роуты и в форме указать через массив model: `[@question, @answer]`

2024-02-16 09:42 UTC, vkurennov commented on config/routes.rb
>    resources :answers
по заданию, ресурс answers должен быть [вложенным](https://guides.rubyonrails.org/routing.html#nested-resources) в questions:

2024-02-16 09:42 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +            answer: FactoryBot.attributes_for(:answer, question_id: question.id, author_id: user.id)
это можно в let вынести

2024-02-16 09:42 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
где тесты на destroy?

2024-02-16 09:42 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
у тебя в destroy условие, значит нужно оба варианта тестировать и для автора и для не-автора. обычно это разными контекстами оформляется

2024-02-16 09:42 UTC, vkurennov commented on spec/features/answer/create_spec.rb
> +    # background do
???
закоментаренные тесты явно не то, что ожидается))

2024-02-16 09:42 UTC, vkurennov commented on spec/features/question/index_spec.rb
> +      FactoryBot.create(:question, title: 'Super question 1', body: 'super_body 1'),
добавь хелперы от FactoryBot и тогда можно просто писать create, attributes_for и т.п. это есть в доке к гему и в скринкасте

2024-02-18 10:03 UTC, kshnyakin commented on app/controllers/questions_controller.rb
> +    if question.author_id == current_user.id
спасибо, заменил!

2024-02-18 10:10 UTC, kshnyakin commented on app/views/answers/_answer.html.erb
> +    <% if current_user&.id == question.author_id %>
Заменил, перевел все на Slim

2024-02-18 10:11 UTC, kshnyakin commented on app/views/answers/_answer.html.erb
> +<tr>
перевел на Slim

2024-02-18 10:16 UTC, kshnyakin commented on spec/controllers/answers_controller_spec.rb
> +            answer: FactoryBot.attributes_for(:answer, question_id: question.id, author_id: user.id)
Спасибо, отрефакторил.

2024-02-18 10:17 UTC, kshnyakin commented on app/views/questions/_question.html.erb
> +    <% if current_user&.id == question.author_id %>
Заменил + перевел шаблон на SLIM

2024-02-18 10:18 UTC, kshnyakin commented on app/controllers/answers_controller.rb
> +    if answer.author_id == current_user.id
Метод модели создал, тесты модели добавил.

2024-02-18 10:29 UTC, kshnyakin commented on spec/features/question/index_spec.rb
> +      FactoryBot.create(:question, title: 'Super question 1', body: 'super_body 1'),
добавил хэлпер (+ везде удалил в коде), знал про него, но на текущей работа есть правило даже, которое запрещает в спеках писать никак иначе, кроме как FactoryBot.create и т.п.

2024-02-19 07:34 UTC, kshnyakin commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
добавил

2024-02-19 07:34 UTC, kshnyakin commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
Добавил разные контексты

2024-02-19 20:05 UTC, kshnyakin commented on spec/features/answer/create_spec.rb
> +    # background do
поправил ситуацию.

2024-02-21 11:52 UTC, vkurennov approved these changes

2024-02-21 11:52 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:question_id, :body, :author_id)
author_id не нужно передавать в запросе, ты его в контроллере можешь установить, используя current_user, иначе можно передать подставной id и создать объект от чужого имени

2024-02-21 11:52 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :body, :author_id)
тут тоже не нужен author_id, используй current_user в контроллере

2024-02-21 12:08 UTC, kshnyakin commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:question_id, :body, :author_id)
спасибо, отрефакторился:

```
  def answer_params
    params.require(:answer).permit(:question_id, :body).merge(author_id: current_user.id)
  end
```

2024-02-21 12:09 UTC, kshnyakin commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :body, :author_id)
поправил:
```
  def question_params
    params.require(:question).permit(:title, :body).merge(author_id: current_user.id)
  end
```

2024-02-21 12:09 UTC, merged